# Generated by Django 5.2.6 on 2025-09-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faucet_reward_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "percentage"),
                            ("AMOUNT", "fixed amount"),
                        ],
                        default="AMOUNT",
                    ),
                ),
                (
                    "faucet_reward_amount",
                    models.DecimalField(
                        decimal_places=18, default=5e-06, max_digits=36
                    ),
                ),
                (
                    "faucet_reward_percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "last_balance",
                    models.DecimalField(decimal_places=18, default=0, max_digits=36),
                ),
            ],
        ),
    ]
