# Generated by Django 5.2.6 on 2025-09-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faucet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="nonce",
            field=models.IntegerField(default=0),
        ),
    ]
