# Generated by Django 5.2.6 on 2025-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faucet", "0002_wallet_nonce"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=255, unique=True)),
                ("recipient", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("nonce", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("MINED", "mined"),
                            ("CONFIRMED", "confirmed"),
                            ("FAILED", "failed"),
                        ],
                        default="PENDING",
                    ),
                ),
                (
                    "gasPrice",
                    models.IntegerField(default=0, help_text="Gas price in wei"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wallet",
            name="maxFeePerGas",
            field=models.IntegerField(
                default=1100000, help_text="Maximum allowed gas price in wei"
            ),
        ),
    ]
