# Generated by Django 5.2.6 on 2025-09-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faucet", "0003_transaction_wallet_maxfeepergas"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="gasUsed",
            field=models.IntegerField(default=0, help_text="Gas used"),
        ),
    ]
